version: '3'
services:
  web:
    image: django.simumkm-playen:0.0.2
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - .env:/app/.env
    extra_hosts:
    - "host.docker.internal:host-gateway"
