# Generated by Django 3.2.9 on 2022-03-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_aktif',
            field=models.CharField(choices=[('T', 'T'), ('F', 'F')], default='F', max_length=1),
        ),
    ]
