# Generated by Django 3.2.9 on 2022-02-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataumkm',
            name='verified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dataumkm',
            name='statusverifikasi',
            field=models.CharField(choices=[('T', 'T'), ('F', 'F'), ('X', 'X')], default='F', max_length=1),
        ),
    ]
