# Generated by Django 3.2.9 on 2021-12-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0002_jenisusaha'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUmkm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_usaha', models.CharField(max_length=50)),
                ('pemilik', models.CharField(blank=True, max_length=50)),
                ('thn_mulai', models.IntegerField(blank=True, max_length=4)),
                ('alamat', models.CharField(blank=True, max_length=255)),
                ('kelurahan_id', models.IntegerField()),
                ('jenis_usaha_id', models.IntegerField()),
                ('namaproduk', models.CharField(blank=True, max_length=100)),
                ('notelepon', models.CharField(blank=True, max_length=20)),
                ('koordinat', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('statusverifikasi', models.CharField(choices=[('T', 'T'), ('F', 'F')], default='F', max_length=1)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dataumkm',
            },
        ),
    ]
