# Generated by Django 3.2.9 on 2021-12-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0003_dataumkm'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataumkm_id', models.IntegerField()),
                ('namaproduk', models.CharField(max_length=100)),
                ('foto', models.CharField(blank=True, max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deskripsi', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'produk',
            },
        ),
    ]
