# Generated by Django 3.2.9 on 2022-02-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0003_dataumkm_catatan_veridikasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataumkm',
            old_name='catatan_veridikasi',
            new_name='catatan_verifikasi',
        ),
    ]
