# Generated by Django 3.2.9 on 2022-02-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0004_rename_catatan_veridikasi_dataumkm_catatan_verifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataumkm',
            name='verified_by',
            field=models.IntegerField(null=True),
        ),
    ]
